import { Navbar } from "@/components/ui/Navbar";
import "./globals.css";
import { Inter } from "next/font/google";
import { Footer } from "@/components/ui/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
 title: "ResellHub | Buy and Sell Sneakers",
 description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
 return (
  <html lang="en">
   <body className={inter.className}>
    <Navbar />
    {children}
    <Footer />
   </body>
  </html>
 );
}
